### ISSUE TITLE
Only returning one title

### ISSUE THREAD

**Issue by ghost** [nimah79/Subscene-API-PHP#4]
On using the example:
$movies = SubScene::search('Fast Five');

I was only getting a return of 1 result: 
Array ( [0] => Array ( [title] => Fast Five - How We Roll (Fast Five) [Album- iDon] (2009) [url] => https://subscene.com/subtitles/fast-five-how-we-roll-fast-five-album-idon ) )

Changing "count($titles)" in the for loop of "subscene.php" to "$titles->length" fixed this for me and correctly returns 15 results.

**Comment by nimah79** [comment]
It's now fixed. Thanks for your report.
